name: CI

on:
  push:

jobs:
  ci:
    name: CI - Análisis y Prueba
    runs-on: ubuntu-latest
    steps:
    - name: Descarga local del repo
      uses: actions/checkout@v4

    - name: configurar node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: npm

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas unitarias
      run: npm test

    - name: Analizar codigo
      run: npm run lint

    - name: subir reporte del análisis
      if: always() #failed() #succes()
      uses: actions/upload-artifact@v4
      with:
        name: cobertura con node 22
        path: coverage/
        retention-days: 2
        if-not-files-found: ignore
        
